1. TO BUILD A CONCEPTUAL MODEL OPEN EXCEL
-> INSERT -> SMART ART -> CYCLE 
	FACT TABLE = SALES TABLE
FIRST I SEE PRODUCT ID SO I CHOOSE 
	DIM TABLE = DIM PRODUCT
NEXT BASED ON CUSTOMER ID 
	DIM TABLE = DIM CUSTOMER
%% DIM CAMPAIGN NOT NECESSARY .. BASED ON YOUR DATA MODEL YOU CAN ADD 
BASED ON ZIPCODE,CITY... WE CREATE DIM GEOGRAPHY

IN POWER BI WE PERFORM A LOT OF TIME INTELLEGENCE AND 
TIME SERIES ANALYSIS AND 
SOME OTHER TREND BASED THINGS.. SO IT IS MANDATORY TO MAKE A 
DIMENSION TABLE BASED ON DATE

FACT : SALES
DIM : DATE,PRODUCT,CUSTOMER,CAMPAIGN,GEOGRAPHY

2. LETS BUILD OUR LOGICAL MODEL

OPEN POWER BI, OPEN SALES.csv,CLICK TRANSFORM DATA

DUPLICATE THE SALES TABLE FOR 3 TIMES

%% IF I CREATE DIMENSION TABLE THE FACT TABLE NO LONGER NEED TO HAVE 
THE DESCRIPTIVE DATA RELATED TO THAT DIM TABLE

3. CREATE DIM PRODUCT

SELECT PRODUCT ID,PRODUCT,CATEGORY,SEGMENT
%% SELECTING UNIT COST AND UNIT PRICE MAY CHANGE BY DIMENSION

SELECT ALL FOUR COLS AND REMOVE DUPLICATES

**
%% CREATE A NEW KEY -> ADD COL -> INDEX COL -> FROM 1
NOW HOW TO ADD THIS NEW KEY TO OUR FACT TABLE
MERGE BASED ON PRODUCT SO THAT WE CAN GET THEM IN OUR FACT AS WELL
%% **

4. CREATE DIM CUSTOMER

CHOOSE COLS : CUSTOMER ID, ZIPCODE, EMAILNAME
REMOVE DUPLICATES
%% THE GEOGRAPHY MAY SAY THE LOCATION OF SHOP,INVENTORY,MAINBRANCH,CUSTOMER LOC
FOR HERE WE HAVE AN EXAMPLE TO CREATE A SNOWFLAKE WE'LL NOT GO WITH IT

SELECT EMAIL..SPLIT COL BY DELIMETER -> CUSTOM -> :_(SPACE) -> LEFT MOST DELIMITER
SAME AGAIN(, ) TO GET LAST AND FIRST NAME 
RENAME AS LAST AND FIRST NAME
REPLACE '(' BY BLANK AND ')' ALSO

5. CREATE DIM GEOGRAPHY

CHOOSE COLS: ZIPCODE,CITY,STATE,DISTRICT,COUNTRY,REGION
REMOVE DUPLICATES

6. DATE TABLE
HOME -> NEW SOURCE -> BLANK QUERY -> ADVANCED EDITOR -> PASTE THE BELOW CODE AND CLICK DONE
//Create Date Dimension
(StartDate as date, EndDate as date)=>

let
    //Capture the date range from the parameters
    StartDate = #date(Date.Year(StartDate), Date.Month(StartDate), 
    Date.Day(StartDate)),
    EndDate = #date(Date.Year(EndDate), Date.Month(EndDate), 
    Date.Day(EndDate)),

    //Get the number of dates that will be required for the table
    GetDateCount = Duration.Days(EndDate - StartDate),

    //Take the count of dates and turn it into a list of dates
    GetDateList = List.Dates(StartDate, GetDateCount, 
    #duration(1,0,0,0)),

    //Convert the list into a table
    DateListToTable = Table.FromList(GetDateList, 
    Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),

    //Create various date attributes from the date column
    //Add Year Column
    YearNumber = Table.AddColumn(DateListToTable, "Year", 
    each Date.Year([Date])),

    //Add Quarter Column
    QuarterNumber = Table.AddColumn(YearNumber , "Quarter", 
    each "Q" & Number.ToText(Date.QuarterOfYear([Date]))),

    //Add Week Number Column
    WeekNumber= Table.AddColumn(QuarterNumber , "Week Number", 
    each Date.WeekOfYear([Date])),

    //Add Month Number Column
    MonthNumber = Table.AddColumn(WeekNumber, "Month Number", 
    each Date.Month([Date])),

    //Add Month Name Column
    MonthName = Table.AddColumn(MonthNumber , "Month", 
    each Date.ToText([Date],"MMMM")),

    //Add Day of Week Column
    DayOfWeek = Table.AddColumn(MonthName , "Day of Week", 
    each Date.ToText([Date],"dddd"))

in
    DayOfWeek 


START DATE 1/1/2011 END DATE 12/31/2024

RENAME THE INVOKED FUNCTION TO Dim Date AND CHANGE THE DATATYPE

7. REMEOVE UNNECESSARY COL FROM SALES TABLE
REPLACE DATE COL'S DATATYPE FROM DATETIME TO DATE -> ADD NEW STEP
CHOOSE COLS : PRODUCT ID,DATE, CUSTOMER ID,CAMPAIGN ID,UNITS,MANUFACTURER ID, MANUFACTURER, UNIT COST, UNIT PRICE
SAVE THE FILE
CLOSE AND APPLY

8. GO TO MODEL VIEW IDENTIFY THE STAR SCHEMA AND SNOWFLAKE 
 DRAG AND DROP THE DATE COL FROM DIM DATE

GO TO DATA RIBBON-> RIGHT CLICK ON DIM DATE -> MAKE AS DATE TABLE


## ADDING MULTIPLE FACT TABLES IN A SINGLE MODEL

## DOES ADDING MULTIPLE FACT TABLES IN A DATA MODEL MAKE IT A SNOWFLAKE SCHEMA? YES IT DEPENDS

LOAD ANOTHER CSV FILE 'FACTBUDGET' .. MAKE THE DATATYPE OF DATE COL FROM DATE/TIME TO DATE

MAKE RELATIONSHIP BETWEEN DIM DATE TO FACTBUDGET TABLE BY DATE COL

MAKE RELATIONSHIP BETWEEN FACTBUDGET AND DIM PRODUCT TABLE
WE HAVE CATEGORY AND SEGMENT COMMON TO BOTH BUT THEY MAKE MANY TO MANY RELATIONSHIP
INORDER TO RECTIFY THAT WE GO POWER QUERY EDITOR AGAIN

9. WE ONLY NEED CATEGORY AND SEGMENT .. SO DUPLICATE THE DIM PRODUCT
NAME IT AS DIM CATSEG
CHOOSE COLS: CATEGORY,SEGMENT
REMOVE DUPLICATES

MAKE A SURROGATE KEY TO MERGE IT WITH FACTBUDGET TABLE
ADD COLUMNS -> INDEX COLUMN -> FROM 1
NAME IT AS CATSEG KEY

WE NEED TO MERGE IT WITH FACT SO SELECT FACTBUDGET -> MERGE QUERIES -> DIM CATSEG 
CATEGORY,SEGMENT -> EXPAND -> CATSEG KEY

DO THE SAME MERGE FOR DIM PRODUCT AND DIM CATSEG AS WELL

WE HAVE CATSEG DIM TABLE SO THERE IS NO NEED TO HAVE SEGMENT AND CATEGORY IN DIM PRODUCT
SO REMOVE THOSE
ALSO FOR FACTBUDGET TABLE


NEW PAGE (LAYOUT) AT THE BOTTOM OF MODEL VIEW 
DRAG AND DROP FACTBUDGET TABLE RIGHT CLICK ON IT -> ADD RELATED TABLE
SAME
SALES TABLE -> ADD RELATED TABLE -> DRAG AND DROP GEOGRAPHY AND CATSEG